# Ad Performance Forecasting Configuration

# Data directories
data:
  raw_dir: data/raw
  processed_dir: data/processed
  models_dir: data/models
  predictions_dir: data/predictions

# Model configuration
model:
  target_column: target_spend_12h
  feature_columns: []
  forecast_horizon: 12
  validation_split: 0.2

# Training configuration
training:
  random_state: 42
  n_trials: 100
  cv_folds: 5

# API configuration (defaults, override with env vars)
api:
  ad_account_id: act_1685189008684458
  graph_version: v19.0
  rate_limit_delay: 2.0
  max_retries: 5
  request_timeout: 60

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/adperf_forecast.log

# Feature engineering
features:
  lag_features: [1, 24, 168]  # hours
  rolling_windows: [7, 14, 30]  # days
  categorical_features: [spend_level, performance_tier]

# Model evaluation
evaluation:
  metrics: [mae, rmse, r2, mape]
  plot_residuals: true
  plot_feature_importance: true
  confidence_intervals: true
